on: [push]

jobs:
    CodeScan:
        runs-on: ubuntu-latest
        steps:
            # Checkout your code repository to scan
            -   name: Checkout repository
                uses: actions/checkout@v2
                with:
                    # We must fetch at least the immediate parents so that if this is
                    # a pull request then we can checkout the head.
                    fetch-depth: 2

            # If this run was triggered by a pull request event, then checkout
            # the head of the pull request instead of the merge commit.
            -   run: git checkout HEAD^2
                if: ${{ github.event_name == 'pull_request' }}

            -   name: Cache files
                uses: actions/cache@v2
                with:
                    path: |
                        ~/.m2
                        ~/.sonar
                    key: ${{ runner.os }}-m2-${{ hashFiles('**/pom.xml') }}
                    restore-keys: ${{ runner.os }}-m2

            -   name: Run Analysis
                uses: borisbsu/codescan-scanner-action@main
                with:
                    login: ${{ secrets.SONAR_LOCAL_TOKEN }}
                    organization: barys-o
                    projectKey: cd-demo-repo
                    codeScanUrl: http://codescan.pagekite.me/
                    args: |
                        sonar.verbose=true

            -   name: Upload SARIF file
                uses: github/codeql-action/upload-sarif@v1
                with:
                    sarif_file: codescan.sarif 
